title: Viswa
description: Essays and notes by Viswanath Sai Muthu.
url: https://mviswanathsai.github.io
baseurl: /essays
timezone: Asia/Kolkata
permalink: /:title/

plugins:
  - jekyll-titles-from-headings

titles_from_headings:
  collections: true
  strip_title: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: essay

exclude:
  - README.md
  - obsidian-plugin
